<?php

namespace Database\Seeders;

use App\Models\Master\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipments = [
            ['type' => 'Forklift', 'model' => 'Zoomlion FB20Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FB15Z'],
            ['type' => 'Truck Mixer', 'model' => 'Sany SY308'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FB25Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FB30Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FB35Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD50Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD60Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD70Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD100Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD15Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD18Z'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD20H'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD25H'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD30H'],
            ['type' => 'Forklift', 'model' => 'Zoomlion FD35H'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS0407DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS0607DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS0808DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS1012DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS1212DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS1414DC'],
            ['type' => 'Scissor Lift', 'model' => 'Zoomlion ZS0812HD'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD220'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD160'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD170'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD320'],
            ['type' => 'Wheel Loader', 'model' => 'Volvo L90GZ'],
            ['type' => 'Wheel Loader', 'model' => 'Volvo L120GZ'],
            ['type' => 'Wheel Loader', 'model' => 'Volvo L220H'],
            ['type' => 'Wheel Loader', 'model' => 'Volvo L350H'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW120'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW140'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW180'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW220'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW310'],
            ['type' => 'Wheel Loader', 'model' => 'Hexindo ZW370'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG916'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L916H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG918'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L918H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L918'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L933'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG933L'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L935H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L936H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG936L'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L936'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG938L'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L938H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L938'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L946'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L946H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG946L'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG LG953'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L956H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L956FH'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L956F'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L958H'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L958F'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L965F'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L968F'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L975F'],
            ['type' => 'Wheel Loader', 'model' => 'SDLG L989F'],
            ['type' => 'Articulated Dump Truck', 'model' => 'BELL B45E'],
            ['type' => 'Articulated Dump Truck', 'model' => 'BELL B50E'],
            ['type' => 'Articulated Dump Truck', 'model' => 'BELL B60E'],
            ['type' => 'Articulated Dump Truck', 'model' => 'Volvo A60H'],
            ['type' => 'Articulated Dump Truck', 'model' => 'Volvo A40G'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac CA30D'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac CA610'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac CP275'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac CC2200'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac CC3800'],
            ['type' => 'Single Drum Roller', 'model' => 'Dynapac SD2500CS'],
            ['type' => 'Dump Truck', 'model' => 'Foton 6X4'],
            ['type' => 'Dump Truck', 'model' => 'Foton 8X4'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ324'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ320'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ346'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ455'],
            ['type' => 'Rigid Dump Truck', 'model' => 'Hexindo EH3500AC'],
            ['type' => 'Rigid Dump Truck', 'model' => 'Hexindo EH4000AC'],
            ['type' => 'Rigid Dump Truck', 'model' => 'Hexindo EH5000AC'],
            ['type' => 'Rigid Dump Truck', 'model' => 'Volvo R100E'],
            ['type' => 'Rigid Dump Truck', 'model' => 'Volvo R60D'],
            ['type' => 'Compactor', 'model' => 'Volvo SD110NE'],
            ['type' => 'Compactor', 'model' => 'Volvo DD100'],
            ['type' => 'Compactor', 'model' => 'Volvo PT220'],
            ['type' => 'Compactor', 'model' => 'Sany SSR120'],
            ['type' => 'Compactor', 'model' => 'Sany SSR220'],
            ['type' => 'Mining Dump Truck', 'model' => 'Zoomlion ZT125G'],
            ['type' => 'Mining Dump Truck', 'model' => 'Zoomlion ZT125A'],
            ['type' => 'Mining Dump Truck', 'model' => 'Zoomlion ZT115A'],
            ['type' => 'Mining Dump Truck', 'model' => 'Zoomlion ZT105A'],
            ['type' => 'Mining Dump Truck', 'model' => 'Zoomlion ZT96A'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC2000'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC1500'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC1100'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC1000'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC800'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC600'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC550'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC350'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC250'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC300'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZTC1300'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC2200'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC850'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC1600'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC600'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC750'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCC550'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZRT1100'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZRT850'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZRT600'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZRT400'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCT900'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCT1500'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCT300'],
            ['type' => 'Truck Crane', 'model' => 'Zoomlion ZCT600'],
            ['type' => 'Road Roller', 'model' => 'SDLG RC730'],
            ['type' => 'Road Roller', 'model' => 'SDLG RD730'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS7120'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS7120H'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS7220'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS7260'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS7260H'],
            ['type' => 'Road Roller', 'model' => 'SDLG RS8140'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9138F'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9165F'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9190F'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9220F'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9290F'],
            ['type' => 'Motor Grader', 'model' => 'SDLG G9240F'],
            ['type' => 'Backhoe Loader', 'model' => 'SDLG B876F'],
            ['type' => 'Backhoe Loader', 'model' => 'SDLG B877F'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD220'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD160'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD170'],
            ['type' => 'Bulldozer', 'model' => 'Zoomlion ZD320'],
            ['type' => 'Skid Steer Loader', 'model' => 'Zoomlion ZS085V'],
            ['type' => 'Skid Steer Loader', 'model' => 'Zoomlion ZS035R'],
            ['type' => 'Skid Steer Loader', 'model' => 'Zoomlion ZS080V'],
            ['type' => 'Skid Steer Loader', 'model' => 'Zoomlion ZS090V'],
            ['type' => 'Crawler Loader', 'model' => 'Zoomlion ZY65C'],
            ['type' => 'Motor Grader', 'model' => 'Sany STG140'],
            ['type' => 'Motor Grader', 'model' => 'Sany STG230 with Backripper'],
            ['type' => 'Tandem Road Roller', 'model' => 'Camino ZC50T'],
            ['type' => 'Crawler Dumper', 'model' => 'Morooka MST-800VD'],
            ['type' => 'All Terrain Crane', 'model' => 'Sany SAC1600'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX33U'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX48U'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX60C'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX65USB'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX70'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX130'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX110MF'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX138MF'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX200'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX210F'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX210MF'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX210LC'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX350H'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX1900'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX330LC'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX2600'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX3600'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX5600'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX8000'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX470LC'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX470LCH'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX490LC'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX870LCH'],
            ['type' => 'Excavator', 'model' => 'Hexindo ZX890LCH'],
            ['type' => 'Excavator', 'model' => 'Hexindo EX2000'],
            ['type' => 'Excavator', 'model' => 'SDLG E6690H'],
            ['type' => 'Excavator', 'model' => 'SDLG ER616F'],
            ['type' => 'Excavator', 'model' => 'SDLG E635F'],
            ['type' => 'Excavator', 'model' => 'SDLG E655F'],
            ['type' => 'Excavator', 'model' => 'SDLG E660FL'],
            ['type' => 'Excavator', 'model' => 'SDLG E680F'],
            ['type' => 'Excavator', 'model' => 'SDLG E690F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6215F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6135F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6138F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6150F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6205F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6210F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6210FLC'],
            ['type' => 'Excavator', 'model' => 'SDLG E6215H'],
            ['type' => 'Excavator', 'model' => 'SDLG E6225F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6250F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6255F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6275F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6300F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6335F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6350F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6375F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6375H'],
            ['type' => 'Excavator', 'model' => 'SDLG E6400F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6460F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6500F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6500FB'],
            ['type' => 'Excavator', 'model' => 'SDLG E6600FB'],
            ['type' => 'Excavator', 'model' => 'SDLG E6650F'],
            ['type' => 'Excavator', 'model' => 'SDLG E6650H'],
            ['type' => 'Excavator', 'model' => 'SDLG E7150F'],
            ['type' => 'Excavator', 'model' => 'Volvo EC55D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC200D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC210D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC300D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC350D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC480D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC750D'],
            ['type' => 'Excavator', 'model' => 'Volvo EC950EL'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE35GU'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE26GU'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE18GU'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE60G'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE75G'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE135'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE215'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE255'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE150'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE210'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE245'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE1250'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE950'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE750'],
            ['type' => 'Cargo', 'model' => 'Cargo'],
            ['type' => 'Wheeled Excavator', 'model' => 'Volvo EW205D'],
            ['type' => 'Mobil', 'model' => 'Toyota Hilux'],
            ['type' => 'Cargo', 'model' => 'Sugarcane Grapple'],
            ['type' => 'Crane Telescopic', 'model' => 'ZOOMLION ZCT600V532'],
            ['type' => 'Vessel', 'model' => 'SDT 90'],
            ['type' => 'Trailer', 'model' => 'Lowbed'],
            ['type' => 'Forklift', 'model' => 'XCMG XCB25-L5-C'],
            ['type' => 'Truck Crane', 'model' => 'XCT160L8'],
            ['type' => 'Digital Produk', 'model' => 'Digital Produk'],
            ['type' => 'Forklift', 'model' => 'Hyundai 30BE-X'],
            ['type' => 'Rent', 'model' => 'Forklift'],
            ['type' => 'Milling Machine', 'model' => 'SCM1000'],
            ['type' => 'Concrete Pump', 'model' => 'Sany SYG5260THB 390C-10 (CP39)'],
            ['type' => 'Excavator', 'model' => 'Zoomlion ZE550G'],
            ['type' => 'Forklift', 'model' => 'Hyundai 20BRP-9'],
            ['type' => 'Crane', 'model' => 'Tadano GR-500'],
            ['type' => 'Crawler Crane', 'model' => 'Sany SCC500'],
            ['type' => 'Motor Grader', 'model' => 'Sany STG230 Wihtout/Non Backripper'],
            ['type' => 'Mobile Truck Crane', 'model' => 'Sany STC2200T7'],
            ['type' => 'Cargo', 'model' => 'Counterweight'],
            ['type' => 'Dump Truck', 'model' => 'Isuzu'],
            ['type' => 'Bulldozer', 'model' => 'Komatsu D85'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ440'],
            ['type' => 'Mobile Truck Crane', 'model' => 'Sany STC250'],
            ['type' => 'Sparepart', 'model' => 'Padfoot SSR220'],
            ['type' => 'Mixer Truck', 'model' => 'Sany SY308'],
            ['type' => 'Wheel Loader', 'model' => 'Cat 950GC'],
            ['type' => 'Excavator', 'model' => 'Kobelco SK200'],
            ['type' => 'Excavator', 'model' => 'Kobelco SK210LC'],
            ['type' => 'Excavator', 'model' => 'ZOOMLION ZE370E'],
            ['type' => 'Dozer', 'model' => 'ZOOMLION ZD260G'],
            ['type' => 'Excavator', 'model' => 'Davelon DX220'],
            ['type' => 'EXCAVATOR', 'model' => 'LIUGONG CLG908E'],
            ['type' => 'TELEHANDLER', 'model' => 'JCB 530-110'],
            ['type' => 'Artileri', 'model' => 'Tank Meriam 155mm/GS M1049A4BE'],
            ['type' => 'Articulated Dump Truck', 'model' => 'Davelon DA45'],
            ['type' => 'Excavator', 'model' => 'SDLG E6350'],
            ['type' => 'Dump Truck', 'model' => 'Sany SYZ331C-8W'],
            ['type' => 'Backhoe Loader', 'model' => 'JCB 3DX Plus'],
            ['type' => 'Motor Grader', 'model' => 'Sany STG265'],
            ['type' => 'Concrete Pump', 'model' => 'Sany YM5181THB30C-8 (CP30)'],
            ['type' => 'Attachment Dozer', 'model' => 'Blade D8TZ'],
            ['type' => 'Wheel Loader', 'model' => 'Liugong CLG856H'],
            ['type' => 'Bulldozer', 'model' => 'Liugong B230'],
            ['type' => 'Wheel Loader', 'model' => 'Liugong 855H'],
            ['type' => 'Cargo', 'model' => 'Electric Scale'],
            ['type' => 'Pickup Truck', 'model' => 'Mitsubishi Triton'],
            ['type' => 'Dozer', 'model' => 'XCMG D170LGP'],
            ['type' => 'Forklift', 'model' => 'HYUNDAI 30DE-7 V300'],
            ['type' => 'Wheel Loader', 'model' => 'Liugong 835H'],
            ['type' => 'Motor Grader', 'model' => 'Liugong 4140D'],
            ['type' => 'Forklift', 'model' => 'Liugong CLG2050H'],
            ['type' => 'Excavator', 'model' => 'LiuGong 906F'],
            ['type' => 'Excavator', 'model' => 'CAT320'],
            ['type' => 'Truck', 'model' => 'Mercy Axor'],
            ['type' => 'Cargo', 'model' => 'Pompa'],
            ['type' => 'Head Trailer', 'model' => 'Volvo'],
            ['type' => 'Excavator', 'model' => 'Komatsu PC200'],
            ['type' => 'Grader', 'model' => 'Komatsu GD535'],
            ['type' => 'Excavator', 'model' => 'Volvo EC550'],
            ['type' => 'Cargo', 'model' => 'Stabilizer'],
            ['type' => 'Excavator', 'model' => 'Sany SY215'],
            ['type' => 'Excavator', 'model' => 'XCMG XE135B'],
            ['type' => 'Truck', 'model' => 'Mercedes Benz Axor 2528C'],
            ['type' => 'Dump Truck', 'model' => 'Hino 260JD'],
            ['type' => 'Wheel Loader', 'model' => 'LiuGong 856HE + Charging Station'],
            ['type' => 'Bulldozer', 'model' => 'LiuGong B160C'],
            ['type' => 'Excavator', 'model' => 'LiuGong 915'],
            ['type' => 'Excavator', 'model' => 'LiuGong 912'],
            ['type' => 'Mobil', 'model' => 'Isuzu D-Max'],
            ['type' => 'Excavator', 'model' => 'XCMG XE75G'],
            ['type' => 'Container', 'model' => '20ft'],
            ['type' => 'Container', 'model' => '40ft'],
            ['type' => 'Excavator', 'model' => 'Hitachi ZX370'],
            ['type' => 'Fokrlift', 'model' => 'Doosan D160S'],
            ['type' => 'Excavator', 'model' => 'LiuGong 920'],
            ['type' => 'Excavator', 'model' => 'CAT 313'],
            ['type' => 'Vibro', 'model' => 'CAT CS20'],
            ['type' => 'Excavator', 'model' => 'Rhino Rex215'],
            ['type' => 'Truck', 'model' => 'Water 20KL'],
            ['type' => 'Mobil', 'model' => 'Toyota Innova'],
            ['type' => 'Crawler Excavator', 'model' => 'XE215G'],
            ['type' => 'Motor Grader', 'model' => 'LiuGong 4230'],
            ['type' => 'Cargo', 'model' => 'Attachment KESLA (Harvester Head)'],
            ['type' => 'Excavator', 'model' => 'JCB 81 NXT'],
            ['type' => 'Dump Truck', 'model' => 'Know How NKM105H'],
            ['type' => 'Dump Truck', 'model' => 'Beiben 9048KK'],
            ['type' => 'Dozer', 'model' => 'SDLG D220HF'],
            ['type' => 'Medium Bus', 'model' => 'Mitsubishi Fuso Canter'],
            ['type' => 'Excavator', 'model' => 'Hyundai HX210HD'],
            ['type' => 'Excavator', 'model' => 'JCB 215LC'],
            ['type' => 'Telehandler', 'model' => 'JCB 541-70'],
            ['type' => 'Wheel Loader', 'model' => 'Liu Gong 816'],
            ['type' => 'Skylift', 'model' => 'Skylift'],
            ['type' => 'Reachstacker', 'model' => 'Kalmar DRU 450'],
            ['type' => 'Compactor', 'model' => 'Sany STR30C-8'],
            ['type' => 'Sparepart', 'model' => ''],
            ['type' => 'Crane', 'model' => 'Sany SRC300T'],
            ['type' => 'Forklift', 'model' => 'Forklift 3.5ton'],
            ['type' => 'Forklift', 'model' => 'LiuGong 8 Ton'],
            ['type' => 'Crane', 'model' => 'Sany STC800'],
            ['type' => 'EXCAVATOR', 'model' => 'Komatsu PC500'],
            ['type' => 'BACKHOE LOADER', 'model' => 'Hitachi BX100'],
            ['type' => 'Excavator', 'model' => 'Komatsu PC300'],
            ['type' => 'Truck', 'model' => 'Axor 2528 CH Euro4'],
            ['type' => 'Excavator', 'model' => 'Kobelco SK330'],
            ['type' => 'Mixer', 'model' => 'Zoomlion 10JBH-R'],
            ['type' => 'Water Tank', 'model' => '25KL'],
            ['type' => 'Motor Grader', 'model' => 'STG170'],
            ['type' => 'Mitsubishi ELF', 'model' => 'ELF'],
            ['type' => 'Truck', 'model' => 'Dongfeng Chasis Truck 6x2 270HP'],
            ['type' => 'Motor Grader', 'model' => 'Liugong 4260'],
            ['type' => 'Dump Truck 10 Roda', 'model' => 'Dongfeng'],
            ['type' => 'Fuel Truck', 'model' => '8 KL'],
            ['type' => '8 KL', 'model' => 'Fuel Truck'],
            ['type' => 'Water Truck 30 KL', 'model' => 'Mercedes-Benz Arocs'],
            ['type' => 'Combine Harvester', 'model' => 'Lovol'],
        ];

        foreach ($equipments as $eq) {
            Equipment::updateOrCreate(
                ['name' => $eq['model']], // Use model as unique identifier
                [
                    'category' => $eq['type'],
                    'description' => $eq['type'].' - '.$eq['model'],
                ]
            );
        }
    }
}
